// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: proto/api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Productattribs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price       int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Weight      string `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Ratings     int32  `protobuf:"varint,5,opt,name=ratings,proto3" json:"ratings,omitempty"`
	Warranty    int32  `protobuf:"varint,6,opt,name=warranty,proto3" json:"warranty,omitempty"`
	Proudctid   string `protobuf:"bytes,7,opt,name=proudctid,proto3" json:"proudctid,omitempty"`
}

func (x *Productattribs) Reset() {
	*x = Productattribs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Productattribs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Productattribs) ProtoMessage() {}

func (x *Productattribs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Productattribs.ProtoReflect.Descriptor instead.
func (*Productattribs) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Productattribs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Productattribs) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Productattribs) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Productattribs) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *Productattribs) GetRatings() int32 {
	if x != nil {
		return x.Ratings
	}
	return 0
}

func (x *Productattribs) GetWarranty() int32 {
	if x != nil {
		return x.Warranty
	}
	return 0
}

func (x *Productattribs) GetProudctid() string {
	if x != nil {
		return x.Proudctid
	}
	return ""
}

type Productlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products *Productattribs `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"`
}

func (x *Productlist) Reset() {
	*x = Productlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Productlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Productlist) ProtoMessage() {}

func (x *Productlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Productlist.ProtoReflect.Descriptor instead.
func (*Productlist) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *Productlist) GetProducts() *Productattribs {
	if x != nil {
		return x.Products
	}
	return nil
}

type Productid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductID string `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
}

func (x *Productid) Reset() {
	*x = Productid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Productid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Productid) ProtoMessage() {}

func (x *Productid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Productid.ProtoReflect.Descriptor instead.
func (*Productid) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *Productid) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type Shopattribs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shopid string `protobuf:"bytes,2,opt,name=shopid,proto3" json:"shopid,omitempty"`
}

func (x *Shopattribs) Reset() {
	*x = Shopattribs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shopattribs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shopattribs) ProtoMessage() {}

func (x *Shopattribs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shopattribs.ProtoReflect.Descriptor instead.
func (*Shopattribs) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *Shopattribs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shopattribs) GetShopid() string {
	if x != nil {
		return x.Shopid
	}
	return ""
}

type Productshopres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopAttribs *Shopattribs `protobuf:"bytes,1,opt,name=shopAttribs,proto3" json:"shopAttribs,omitempty"`
}

func (x *Productshopres) Reset() {
	*x = Productshopres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Productshopres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Productshopres) ProtoMessage() {}

func (x *Productshopres) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Productshopres.ProtoReflect.Descriptor instead.
func (*Productshopres) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *Productshopres) GetShopAttribs() *Shopattribs {
	if x != nil {
		return x.ShopAttribs
	}
	return nil
}

type Productlistreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serviceable bool `protobuf:"varint,1,opt,name=serviceable,proto3" json:"serviceable,omitempty"`
}

func (x *Productlistreq) Reset() {
	*x = Productlistreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Productlistreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Productlistreq) ProtoMessage() {}

func (x *Productlistreq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Productlistreq.ProtoReflect.Descriptor instead.
func (*Productlistreq) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *Productlistreq) GetServiceable() bool {
	if x != nil {
		return x.Serviceable
	}
	return false
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long float32 `protobuf:"fixed32,1,opt,name=long,proto3" json:"long,omitempty"`
	Lat  float32 `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *Coordinates) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *Coordinates) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type Shopcords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopCords *Coordinates `protobuf:"bytes,1,opt,name=shopCords,proto3" json:"shopCords,omitempty"`
}

func (x *Shopcords) Reset() {
	*x = Shopcords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shopcords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shopcords) ProtoMessage() {}

func (x *Shopcords) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shopcords.ProtoReflect.Descriptor instead.
func (*Shopcords) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *Shopcords) GetShopCords() *Coordinates {
	if x != nil {
		return x.ShopCords
	}
	return nil
}

type Shopres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopAttribs *Shopattribs `protobuf:"bytes,1,opt,name=shopAttribs,proto3" json:"shopAttribs,omitempty"`
}

func (x *Shopres) Reset() {
	*x = Shopres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shopres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shopres) ProtoMessage() {}

func (x *Shopres) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shopres.ProtoReflect.Descriptor instead.
func (*Shopres) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *Shopres) GetShopAttribs() *Shopattribs {
	if x != nil {
		return x.ShopAttribs
	}
	return nil
}

type Userreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Userreq) Reset() {
	*x = Userreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userreq) ProtoMessage() {}

func (x *Userreq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userreq.ProtoReflect.Descriptor instead.
func (*Userreq) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *Userreq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Userres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Shopid string `protobuf:"bytes,3,opt,name=shopid,proto3" json:"shopid,omitempty"`
}

func (x *Userres) Reset() {
	*x = Userres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userres) ProtoMessage() {}

func (x *Userres) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userres.ProtoReflect.Descriptor instead.
func (*Userres) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *Userres) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Userres) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Userres) GetShopid() string {
	if x != nil {
		return x.Shopid
	}
	return ""
}

var File_proto_api_proto protoreflect.FileDescriptor

var file_proto_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x22, 0xc8, 0x01, 0x0a, 0x0e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x61, 0x72, 0x72, 0x61, 0x6e, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77,
	0x61, 0x72, 0x72, 0x61, 0x6e, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x75, 0x64,
	0x63, 0x74, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x75,
	0x64, 0x63, 0x74, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x29, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x69, 0x64, 0x22,
	0x48, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x68, 0x6f, 0x70, 0x72, 0x65,
	0x73, 0x12, 0x36, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x52, 0x0b, 0x73, 0x68,
	0x6f, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x22, 0x32, 0x0a, 0x0e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x72, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x33, 0x0a,
	0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x22, 0x3f, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x32, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x41, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x72, 0x65, 0x73, 0x12, 0x36,
	0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x70, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x22, 0x1f, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x4b, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x72,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x6f, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68,
	0x6f, 0x70, 0x69, 0x64, 0x32, 0x90, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x67, 0x72, 0x69,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x2e, 0x61, 0x67, 0x72,
	0x69, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x1a, 0x17,
	0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x68, 0x6f, 0x70, 0x72, 0x65, 0x73, 0x32, 0x44, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61,
	0x72, 0x42, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x12, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x10, 0x2e, 0x61, 0x67,
	0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x72, 0x65, 0x73, 0x32, 0x43, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x61, 0x67, 0x72, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x72,
	0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData = file_proto_api_proto_rawDesc
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_proto_rawDescData)
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_api_proto_goTypes = []interface{}{
	(*Productattribs)(nil), // 0: agriapi.productattribs
	(*Productlist)(nil),    // 1: agriapi.productlist
	(*Productid)(nil),      // 2: agriapi.productid
	(*Shopattribs)(nil),    // 3: agriapi.shopattribs
	(*Productshopres)(nil), // 4: agriapi.productshopres
	(*Productlistreq)(nil), // 5: agriapi.productlistreq
	(*Coordinates)(nil),    // 6: agriapi.coordinates
	(*Shopcords)(nil),      // 7: agriapi.shopcords
	(*Shopres)(nil),        // 8: agriapi.shopres
	(*Userreq)(nil),        // 9: agriapi.userreq
	(*Userres)(nil),        // 10: agriapi.userres
}
var file_proto_api_proto_depIdxs = []int32{
	0,  // 0: agriapi.productlist.products:type_name -> agriapi.productattribs
	3,  // 1: agriapi.productshopres.shopAttribs:type_name -> agriapi.shopattribs
	6,  // 2: agriapi.shopcords.shopCords:type_name -> agriapi.coordinates
	3,  // 3: agriapi.shopres.shopAttribs:type_name -> agriapi.shopattribs
	5,  // 4: agriapi.ProductService.GetProductList:input_type -> agriapi.productlistreq
	2,  // 5: agriapi.ProductService.GetByProduct:input_type -> agriapi.productid
	7,  // 6: agriapi.ShopService.GetNearByShop:input_type -> agriapi.shopcords
	9,  // 7: agriapi.UserService.GetNearestUser:input_type -> agriapi.userreq
	1,  // 8: agriapi.ProductService.GetProductList:output_type -> agriapi.productlist
	4,  // 9: agriapi.ProductService.GetByProduct:output_type -> agriapi.productshopres
	8,  // 10: agriapi.ShopService.GetNearByShop:output_type -> agriapi.shopres
	10, // 11: agriapi.UserService.GetNearestUser:output_type -> agriapi.userres
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Productattribs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Productlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Productid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shopattribs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Productshopres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Productlistreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shopcords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shopres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_rawDesc = nil
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
